<?php

/**
 * PacientesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PacientesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PacientesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pacientes');
    }
}