<?php

/**
 * UsuariosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuariosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuariosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Usuarios');
    }
}